### ISSUE TITLE
Fix workaround added to Logo.java

### ISSUE THREAD

**Issue by dluc** [Azure/pcs-config-java#41] opened 2017-09-30 02:08 UTC
# Type of issue

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description

See code, remove hardcoded logo

https://github.com/Azure/pcs-config-java/blob/master/app/com/microsoft/azure/iotsolutions/uiconfig/services/models/Logo.java

**Comment by zhang-hua** [comment] 2017-10-31 10:05
This bug is caused by the sbt build script which will ignore the resource file under java source folder. So the jar file won't contain the default logo file. We fix it to create a separate resource folder and move resource files (DefaultLogo.svg, default.json) to that folder. And add a config setting `unmanagedResourceDirectories` in `build.sbt` to use that folder.

**Comment by zhang-hua** [comment] 2017-11-20 02:25
close it since it has been fixed in PR #51.

**Closed by zhang-hua** 2017-11-20 02:25 UTC
Labels: bug
